//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHost.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ia.com/wcf", ConfigurationName="ServiceReference1.WeatherReport")]
    public interface WeatherReport {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ia.com/wcf/WeatherReport/GetCurrentTemp", ReplyAction="http://www.ia.com/wcf/WeatherReport/GetCurrentTempResponse")]
        int GetCurrentTemp(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ia.com/wcf/WeatherReport/Getforecast", ReplyAction="http://www.ia.com/wcf/WeatherReport/GetforecastResponse")]
        TemperatureServiceLibrary.Forecast Getforecast(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ia.com/wcf/WeatherReport/SaveForecast", ReplyAction="http://www.ia.com/wcf/WeatherReport/SaveForecastResponse")]
        void SaveForecast(TemperatureServiceLibrary.Forecast forecast);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeatherReportChannel : WebHost.ServiceReference1.WeatherReport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherReportClient : System.ServiceModel.ClientBase<WebHost.ServiceReference1.WeatherReport>, WebHost.ServiceReference1.WeatherReport {
        
        public WeatherReportClient() {
        }
        
        public WeatherReportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherReportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherReportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherReportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetCurrentTemp(string city) {
            return base.Channel.GetCurrentTemp(city);
        }
        
        public TemperatureServiceLibrary.Forecast Getforecast(string city) {
            return base.Channel.Getforecast(city);
        }
        
        public void SaveForecast(TemperatureServiceLibrary.Forecast forecast) {
            base.Channel.SaveForecast(forecast);
        }
    }
}
