//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsClient.TemperatureService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Forecast", Namespace="http://www.ia.com/wcf")]
    [System.SerializableAttribute()]
    public partial class Forecast : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day1DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Day1HighField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Day1LowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Day2DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Day2HighField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Day2LowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day1Details {
            get {
                return this.Day1DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.Day1DetailsField, value) != true)) {
                    this.Day1DetailsField = value;
                    this.RaisePropertyChanged("Day1Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Day1High {
            get {
                return this.Day1HighField;
            }
            set {
                if ((this.Day1HighField.Equals(value) != true)) {
                    this.Day1HighField = value;
                    this.RaisePropertyChanged("Day1High");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Day1Low {
            get {
                return this.Day1LowField;
            }
            set {
                if ((this.Day1LowField.Equals(value) != true)) {
                    this.Day1LowField = value;
                    this.RaisePropertyChanged("Day1Low");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day2Details {
            get {
                return this.Day2DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.Day2DetailsField, value) != true)) {
                    this.Day2DetailsField = value;
                    this.RaisePropertyChanged("Day2Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Day2High {
            get {
                return this.Day2HighField;
            }
            set {
                if ((this.Day2HighField.Equals(value) != true)) {
                    this.Day2HighField = value;
                    this.RaisePropertyChanged("Day2High");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Day2Low {
            get {
                return this.Day2LowField;
            }
            set {
                if ((this.Day2LowField.Equals(value) != true)) {
                    this.Day2LowField = value;
                    this.RaisePropertyChanged("Day2Low");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ia.com/wcf", ConfigurationName="TemperatureService.WeatherReport")]
    public interface WeatherReport {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ia.com/wcf/WeatherReport/GetCurrentTemp", ReplyAction="http://www.ia.com/wcf/WeatherReport/GetCurrentTempResponse")]
        int GetCurrentTemp(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ia.com/wcf/WeatherReport/Getforecast", ReplyAction="http://www.ia.com/wcf/WeatherReport/GetforecastResponse")]
        WindowsClient.TemperatureService.Forecast Getforecast(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ia.com/wcf/WeatherReport/SaveForecast", ReplyAction="http://www.ia.com/wcf/WeatherReport/SaveForecastResponse")]
        void SaveForecast(WindowsClient.TemperatureService.Forecast forecast);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeatherReportChannel : WindowsClient.TemperatureService.WeatherReport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherReportClient : System.ServiceModel.ClientBase<WindowsClient.TemperatureService.WeatherReport>, WindowsClient.TemperatureService.WeatherReport {
        
        public WeatherReportClient() {
        }
        
        public WeatherReportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherReportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherReportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherReportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetCurrentTemp(string city) {
            return base.Channel.GetCurrentTemp(city);
        }
        
        public WindowsClient.TemperatureService.Forecast Getforecast(string city) {
            return base.Channel.Getforecast(city);
        }
        
        public void SaveForecast(WindowsClient.TemperatureService.Forecast forecast) {
            base.Channel.SaveForecast(forecast);
        }
    }
}
