//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsClient.CustomerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerService.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/ListCustomers", ReplyAction="http://tempuri.org/ICustomerService/ListCustomersResponse")]
        CustomerServiceLibrary.Customer[] ListCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerDetails", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerDetailsResponse")]
        CustomerServiceLibrary.CustomerDetail GetCustomerDetails(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/SaveChanges", ReplyAction="http://tempuri.org/ICustomerService/SaveChangesResponse")]
        bool SaveChanges(int customerId, string FirstName, string LastName, string Address);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : WindowsClient.CustomerService.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<WindowsClient.CustomerService.ICustomerService>, WindowsClient.CustomerService.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CustomerServiceLibrary.Customer[] ListCustomers() {
            return base.Channel.ListCustomers();
        }
        
        public CustomerServiceLibrary.CustomerDetail GetCustomerDetails(int customerId) {
            return base.Channel.GetCustomerDetails(customerId);
        }
        
        public bool SaveChanges(int customerId, string FirstName, string LastName, string Address) {
            return base.Channel.SaveChanges(customerId, FirstName, LastName, Address);
        }
    }
}
